### ISSUE TITLE
Question about the output of concatenate 

### ISSUE THREAD

**Issue by CYL586309** [tangjianpku/LINE#34]
From the section 4.1.3 of LINE paper, the first-order proximity and second-order proximity can be preserved by concatenating two embedding vectors of each node. I use concatenate.cpp and obtain a UNIX executable file which produces the final embedding. However, I notice that the embedding vector of each nodes is different from simply combining the first-order and second-order embedding vectors, so I'm curious about the way of concatenating the first-order and second-order embedding vectors. can the authors answer that?

**Comment by mnqu** [comment]
Thanks for your attention to our work. In practice, the l2 norms of vectors learned with the first- and second-order proximities can be very different, so directly concatenating them may yield inferior results. Therefore, we first normalize both vectors to unit vectors, before concatenating them for classification.

**Comment by CYL586309** [comment]
Thanks for your answer, I totally understand the values of final embedding.

**Comment by CYL586309** [comment]
we should focus on the difference between different nodes on same embedding, but not on the first- and second order embedding. so I think we can simply normalize the embedding and then concatenate the two kinds of embedding, which also consider first- and second order proximities.
